package me.jessyan.peach.shop.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.jessyan.peach.shop.entity.search.UserSearchRecordBean;
import me.jessyan.peach.shop.entity.search.SearchRecordBean;

import me.jessyan.peach.shop.greendao.UserSearchRecordBeanDao;
import me.jessyan.peach.shop.greendao.SearchRecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userSearchRecordBeanDaoConfig;
    private final DaoConfig searchRecordBeanDaoConfig;

    private final UserSearchRecordBeanDao userSearchRecordBeanDao;
    private final SearchRecordBeanDao searchRecordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userSearchRecordBeanDaoConfig = daoConfigMap.get(UserSearchRecordBeanDao.class).clone();
        userSearchRecordBeanDaoConfig.initIdentityScope(type);

        searchRecordBeanDaoConfig = daoConfigMap.get(SearchRecordBeanDao.class).clone();
        searchRecordBeanDaoConfig.initIdentityScope(type);

        userSearchRecordBeanDao = new UserSearchRecordBeanDao(userSearchRecordBeanDaoConfig, this);
        searchRecordBeanDao = new SearchRecordBeanDao(searchRecordBeanDaoConfig, this);

        registerDao(UserSearchRecordBean.class, userSearchRecordBeanDao);
        registerDao(SearchRecordBean.class, searchRecordBeanDao);
    }
    
    public void clear() {
        userSearchRecordBeanDaoConfig.clearIdentityScope();
        searchRecordBeanDaoConfig.clearIdentityScope();
    }

    public UserSearchRecordBeanDao getUserSearchRecordBeanDao() {
        return userSearchRecordBeanDao;
    }

    public SearchRecordBeanDao getSearchRecordBeanDao() {
        return searchRecordBeanDao;
    }

}
